name: Manual Helm Library Release (gh-pages)

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from Chart.yaml
        id: chart
        run: |
          version=$(grep '^version:' lib/Chart.yaml | awk '{print $2}')
          echo "chart_version=$version" >> "$GITHUB_OUTPUT"

      - name: Check if release already exists
        run: |
          tag="v${{ steps.chart.outputs.chart_version }}"
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/$tag)
          if [ "$response" -eq 200 ]; then
            echo "❌ Release with tag $tag already exists!"
            exit 1
          fi

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: |
          mkdir -p .build
          helm package lib --destination .build

      - name: Prepare gh-pages
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages gh-pages

      - name: Update index.yaml and push to gh-pages
        run: |
          cd gh-pages
          cp ../.build/*.tgz .
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }} --merge index.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Publish chart version ${{ steps.chart.outputs.chart_version }}" || echo "No changes"
          git push origin gh-pages
          
      - name: Wait for GitHub Pages deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "⏳ Waiting for GitHub Pages deployment to complete..."

          
          for i in {1..20}; do
            echo "Checking deployment status..."
            response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/pages)
            
            echo "Full API Response:"
            echo "$response" | jq '.'
            
            status=$(echo "$response" | jq -r '.status')
            error=$(echo "$response" | jq -r '.error.message // empty')
            
            echo "Attempt $i: status = $status"
            
            if [ "$status" = "built" ]; then
              echo "✅ GitHub Pages built successfully."
              exit 0
            elif [ "$status" = "null" ] || [ "$status" = "404" ]; then
              echo "⏳ Deployment not started yet. Waiting..."
            elif [ -n "$error" ]; then
              echo "❌ Deployment error: $error"
              exit 1
            else
              echo "⏳ Still building... ($status)"
            fi
            
            sleep 10
          done
          
          echo "❌ Timed out waiting for GitHub Pages deployment."
          exit 1

      - name: Upload Helm package to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.chart.outputs.chart_version }}
          name: Helm library v${{ steps.chart.outputs.chart_version }}
          body: |
            Helm chart released.

            📦 Helm repo: [index.yaml](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.yaml)
          files: .build/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
