name: Release Helm Library

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Chart version to release (e.g. 0.1.0)'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package Helm library
        run: |
          mkdir -p .build
          helm package lib --destination .build

      - name: Update Helm repo index in docs/
        run: |
          mkdir -p docs
          helm repo index .build --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }} --merge docs/index.yaml
          mv .build/*.tgz docs/
          mv .build/index.yaml docs/index.yaml

      - name: Commit and push changes to docs/
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Release Helm library version ${{ github.event.inputs.release_version }}"
          git push origin main
